# Generated by Django 4.0.3 on 2022-03-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=100)),
                ('units', models.CharField(default='%', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='This',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1000)),
                ('variable', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='That',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=50)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.actuator')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('that', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.that')),
                ('this', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.this')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.user')),
            ],
        ),
        migrations.AddField(
            model_name='actuator',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sa.brand'),
        ),
    ]
