# Generated by Django 4.0.3 on 2022-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='this',
            name='originalcommand',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
