# Generated by Django 4.0.3 on 2022-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0002_this_originalcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='this',
            name='originalcommand',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
