# Generated by Django 4.0.3 on 2022-04-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0003_alter_this_originalcommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='this',
            name='originalcommand',
        ),
    ]
